package main

import (
	"bufio"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"text/template"
)

var errDownload = errors.New("unable to download confusables")

const (
	base    = 16
	bitsize = 64
	url     = "https://www.unicode.org/Public/security/latest/confusables.txt"
)

const sourceFile = `package confusables

// THIS FILE WAS AUTOGENERATED - DO NOT EDIT

var confusables = map[rune]string{
{{- range $key, $value := .Confusables}}
	{{ $key }}: {{ $value }},
{{- end}}
}

var descriptions = map[string]string{
{{- range $key, $value := .Descriptions}}
	{{ $key }}: {{ $value }},
{{- end}}
}
`

func main() {
	if err := buildTable(); err != nil {
		log.Fatal("unable to build tables")
	}
}

func buildTable() error {
	resp, err := http.Get(url)
	if err != nil {
		return err
	}

	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return errDownload
	}

	confusables := map[string]string{}
	descriptions := map[string]string{}

	// Extract confusables from downloaded file
	scanner := bufio.NewScanner(resp.Body)
	for scanner.Scan() {
		parseLine(scanner.Text(), confusables, descriptions)
	}

	amendments, err := os.Open("scripts/amendments.txt")
	if err != nil {
		return err
	}

	defer amendments.Close()

	scanner = bufio.NewScanner(amendments)
	for scanner.Scan() {
		parseLine(scanner.Text(), confusables, descriptions)
	}

	// Output a mapping file
	tmpl := template.New("tables.go")

	tmpl, err = tmpl.Parse(sourceFile)
	if err != nil {
		return fmt.Errorf("unable to parse template: %w", err)
	}

	f, err := os.Create("tables.go")
	if err != nil {
		return fmt.Errorf("unable to create tables.go: %w", err)
	}

	defer f.Close()

	if err := tmpl.Execute(f, struct {
		Confusables  map[string]string
		Descriptions map[string]string
	}{
		Confusables:  confusables,
		Descriptions: descriptions,
	}); err != nil {
		return fmt.Errorf("unable to execute template: %w", err)
	}

	return nil
}

func parseLine(line string, confusables map[string]string, descriptions map[string]string) {
	// Remove BOM, skip comments and blank lines
	line = strings.TrimPrefix(line, string([]byte{0xEF, 0xBB, 0xBF}))
	if strings.HasPrefix(line, "#") || line == "" {
		return
	}

	// Extract source -> target mapping
	fields := strings.Split(line, " ;\t")
	source := codepointsToRunes(fields[0])
	target := string(codepointsToRunes(fields[1]))

	sourceStr := string(source)
	if _, ok := descriptions[sourceStr]; !ok {
		descriptions[strconv.Quote(sourceStr)] =
			strconv.Quote(strings.TrimSpace(strings.Split(strings.Split(fields[2], " → ")[1], " ) ")[1]))
	}

	if _, ok := descriptions[target]; !ok {
		descriptions[strconv.Quote(target)] =
			strconv.Quote(strings.TrimSpace(strings.Split(strings.Split(fields[2], " → ")[2], "#")[0]))
	}

	confusables[fmt.Sprintf("0x%.8X", source[0])] = fmt.Sprintf("%+q", target)
}

func codepointsToRunes(s string) []rune {
	codePoints := strings.Split(s, " ")

	runes := make([]rune, 0, len(codePoints))

	for _, unicodeCodePoint := range codePoints {
		codePoint, err := strconv.ParseUint(unicodeCodePoint, base, bitsize)
		if err != nil {
			log.Fatal(err)
		}

		runes = append(runes, rune(codePoint))
	}

	return runes
}
