package main

import (
	"bufio"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"text/template"
)

const url = "https://www.unicode.org/Public/security/latest/confusables.txt"
const sourceFile = `package confusables

// THIS FILE WAS AUTOGENERATED - DO NOT EDIT

var confusables = map[rune]string{
{{- range .}}
	{{ . -}}
{{end}}
}
`

func main() {
	// Download the file
	resp, err := http.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		log.Fatalf("No successful response for %s", url)
	}

	// Extract confusables from downloaded file
	scanner := bufio.NewScanner(resp.Body)
	var confusables []string
	for scanner.Scan() {
		line := scanner.Text()

		// Remove BOM, skip comments and blank lines
		line = strings.TrimPrefix(line, string([]byte{0xEF, 0xBB, 0xBF}))
		if strings.HasPrefix(line, "#") || line == "" {
			continue
		}

		// Extract source -> target mapping
		fields := strings.Split(line, " ;\t")
		source := codePointToString(fields[0])
		target := codePointToString(fields[1])
		entry := fmt.Sprintf("0x%.8X: %+q,", source[0], string(target))

		confusables = append(confusables, entry)
	}

	// Output a mapping file
	tmpl := template.New("tables.go")
	tmpl, err = tmpl.Parse(sourceFile)
	if err != nil {
		log.Fatal(err)
	}

	f, err := os.Create("tables.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	err = tmpl.Execute(f, confusables)
	if err != nil {
		log.Fatal(err)
	}
}

func codePointToString(s string) []rune {
	var runes []rune
	for _, unicodeCodePoint := range strings.Split(s, " ") {
		codePoint, err := strconv.ParseUint(unicodeCodePoint, 16, 64)
		if err != nil {
			log.Fatal(err)
		}

		runes = append(runes, rune(codePoint))
	}

	return runes
}
